---
- name: Remove adminer editor PHP artefacts
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ adminer_editor_internal.pkg_entry_point }}"
    - "{{ adminer_editor_internal.pkg_dest }}"
    - "{{ adminer_editor.document_root }}"
