---
- name: Check service
  stat: path={{ mailhog.service_script }}
  register: mailhog_service_check

- name: Stop service
  become: yes
  service: name=mailhog state=stopped
  when: mailhog_service_check.stat.exists

- name: Remove mailhog files
  become: true
  file: path={{ item }} state=absent
  with_items:
    - "{{ mailhog.pkg_dest }}"
    - "{{ mailhog.sendmail_dest }}"
    - "{{ mailhog.system_sendmail_path }}"
    - "{{ mailhog.start_script }}"
    - "{{ mailhog.service_script }}"
